--- 
apiVersion: v1
kind: Pod
metadata: 
  name: server
spec: 
  containers: 
    - 
      image: nginx
      name: nginx
      volumeMounts: 
        - 
          mountPath: /git-repo
          name: git-volume
  volumes: 
    - 
      gitRepo: 
        repository: "https://github.com/dvohra/kubernetes-volume.git"
        revision: 22f1d8406d464b0c0874075539c1f2e96c253775
      name: git-volume